services:
    odoo15:
        image: odoo:15.0
        container_name: app
        depends_on:
            - db
        ports:
            - "8069:8069"
        #command: odoo -u modulo -d odoo
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/addons
        restart: always
        networks:
            - odoo-net

    db:
        image: postgres:13
        container_name: odoo15-db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=myodoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
        restart: always
        ports:
            - "5434:5432"
        networks:
            - odoo-net
volumes:
    odoo-web-data:
    odoo-db-data:

networks:
    odoo-net:
        name: odoo-net
        driver: bridge
